// Generated by gencpp from file robot_operation/powerState.msg
// DO NOT EDIT!


#ifndef ROBOT_OPERATION_MESSAGE_POWERSTATE_H
#define ROBOT_OPERATION_MESSAGE_POWERSTATE_H

#include <ros/service_traits.h>


#include <robot_operation/powerStateRequest.h>
#include <robot_operation/powerStateResponse.h>


namespace robot_operation
{

struct powerState
{

typedef powerStateRequest Request;
typedef powerStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct powerState
} // namespace robot_operation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_operation::powerState > {
  static const char* value()
  {
    return "e169ea722c6db37813a8d2b875c7d996";
  }

  static const char* value(const ::robot_operation::powerState&) { return value(); }
};

template<>
struct DataType< ::robot_operation::powerState > {
  static const char* value()
  {
    return "robot_operation/powerState";
  }

  static const char* value(const ::robot_operation::powerState&) { return value(); }
};


// service_traits::MD5Sum< ::robot_operation::powerStateRequest> should match
// service_traits::MD5Sum< ::robot_operation::powerState >
template<>
struct MD5Sum< ::robot_operation::powerStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_operation::powerState >::value();
  }
  static const char* value(const ::robot_operation::powerStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_operation::powerStateRequest> should match
// service_traits::DataType< ::robot_operation::powerState >
template<>
struct DataType< ::robot_operation::powerStateRequest>
{
  static const char* value()
  {
    return DataType< ::robot_operation::powerState >::value();
  }
  static const char* value(const ::robot_operation::powerStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_operation::powerStateResponse> should match
// service_traits::MD5Sum< ::robot_operation::powerState >
template<>
struct MD5Sum< ::robot_operation::powerStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_operation::powerState >::value();
  }
  static const char* value(const ::robot_operation::powerStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_operation::powerStateResponse> should match
// service_traits::DataType< ::robot_operation::powerState >
template<>
struct DataType< ::robot_operation::powerStateResponse>
{
  static const char* value()
  {
    return DataType< ::robot_operation::powerState >::value();
  }
  static const char* value(const ::robot_operation::powerStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_OPERATION_MESSAGE_POWERSTATE_H
