// Generated by gencpp from file robot_operation/temperature.msg
// DO NOT EDIT!


#ifndef ROBOT_OPERATION_MESSAGE_TEMPERATURE_H
#define ROBOT_OPERATION_MESSAGE_TEMPERATURE_H

#include <ros/service_traits.h>


#include <robot_operation/temperatureRequest.h>
#include <robot_operation/temperatureResponse.h>


namespace robot_operation
{

struct temperature
{

typedef temperatureRequest Request;
typedef temperatureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct temperature
} // namespace robot_operation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_operation::temperature > {
  static const char* value()
  {
    return "708df609bf4c0f5f446cfd5c1c3b552e";
  }

  static const char* value(const ::robot_operation::temperature&) { return value(); }
};

template<>
struct DataType< ::robot_operation::temperature > {
  static const char* value()
  {
    return "robot_operation/temperature";
  }

  static const char* value(const ::robot_operation::temperature&) { return value(); }
};


// service_traits::MD5Sum< ::robot_operation::temperatureRequest> should match
// service_traits::MD5Sum< ::robot_operation::temperature >
template<>
struct MD5Sum< ::robot_operation::temperatureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_operation::temperature >::value();
  }
  static const char* value(const ::robot_operation::temperatureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_operation::temperatureRequest> should match
// service_traits::DataType< ::robot_operation::temperature >
template<>
struct DataType< ::robot_operation::temperatureRequest>
{
  static const char* value()
  {
    return DataType< ::robot_operation::temperature >::value();
  }
  static const char* value(const ::robot_operation::temperatureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_operation::temperatureResponse> should match
// service_traits::MD5Sum< ::robot_operation::temperature >
template<>
struct MD5Sum< ::robot_operation::temperatureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_operation::temperature >::value();
  }
  static const char* value(const ::robot_operation::temperatureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_operation::temperatureResponse> should match
// service_traits::DataType< ::robot_operation::temperature >
template<>
struct DataType< ::robot_operation::temperatureResponse>
{
  static const char* value()
  {
    return DataType< ::robot_operation::temperature >::value();
  }
  static const char* value(const ::robot_operation::temperatureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_OPERATION_MESSAGE_TEMPERATURE_H
