// Generated by gencpp from file robot_operation/temperatureResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_OPERATION_MESSAGE_TEMPERATURERESPONSE_H
#define ROBOT_OPERATION_MESSAGE_TEMPERATURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_operation
{
template <class ContainerAllocator>
struct temperatureResponse_
{
  typedef temperatureResponse_<ContainerAllocator> Type;

  temperatureResponse_()
    {
    }
  temperatureResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::robot_operation::temperatureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_operation::temperatureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct temperatureResponse_

typedef ::robot_operation::temperatureResponse_<std::allocator<void> > temperatureResponse;

typedef boost::shared_ptr< ::robot_operation::temperatureResponse > temperatureResponsePtr;
typedef boost::shared_ptr< ::robot_operation::temperatureResponse const> temperatureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_operation::temperatureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_operation::temperatureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace robot_operation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_operation::temperatureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_operation::temperatureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_operation::temperatureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_operation::temperatureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_operation::temperatureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_operation::temperatureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_operation::temperatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::robot_operation::temperatureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_operation::temperatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_operation/temperatureResponse";
  }

  static const char* value(const ::robot_operation::temperatureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_operation::temperatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::robot_operation::temperatureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_operation::temperatureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct temperatureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_operation::temperatureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robot_operation::temperatureResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_OPERATION_MESSAGE_TEMPERATURERESPONSE_H
