(cl:defpackage robot_operation-srv
  (:use )
  (:export
   "POWERSTATE"
   "<POWERSTATE-REQUEST>"
   "POWERSTATE-REQUEST"
   "<POWERSTATE-RESPONSE>"
   "POWERSTATE-RESPONSE"
   "TEMPERATURE"
   "<TEMPERATURE-REQUEST>"
   "TEMPERATURE-REQUEST"
   "<TEMPERATURE-RESPONSE>"
   "TEMPERATURE-RESPONSE"
  ))

